# C151D22: data for CHEM151. Don't run this file.
D=(
"ABOUT\nChem 151 Formula Sheet -- Chemical Thinking Vol. I\n\nCONTENT"
"S (modules and units)\n\n0. CONSTANTS AND CONVERSIONS\n* 0.1 Constan"
"ts\n* 0.2 Conversions\n* 0.3 Factor-label method (works for every "
"unit problem)\n\n1. UNIT 1 (M1-M2): PHASES, SEPARATIONS, PARTICULATE"
" MODEL\n* 1.1 Differentiating characteristics\n* 1.2 Heating / cooli"
"ng curves (T vs t) and DeltaE vs T\n* 1.3 Phase diagrams (P vs T)\n*"
" 1.4 Vapor pressure and boiling\n* 1.5 Separation techniques\n* "
"1.6 Particulate model of matter\n* 1.7 Ideal gases\n* 1.8 Potential "
"energy and phase changes\n* 1.9 PEC (potential energy-configuration)"
" diagrams\n* 1.10 Emergent properties and common traps\n\n2. UNIT "
"1 (M3-M4): COUNTING PARTICLES, GASES, COMPOSITION\n* 2.1 Classifying"
" matter (+ naming binary compounds)\n* 2.2 Mass <-> moles <-> partic"
"les\n* 2.3 Solutions and concentration\n* 2.4 Ideal gas law (molar "
"form) (+ other Unit 1 ratio problems)\n* 2.5 Subatomic model\n* "
"2.6 Average atomic mass from isotopes\n* 2.7 Reading mass spectra\n*"
" 2.8 Empirical and molecular formulas (combustion analysis) (+ mass "
"percent from a formula)\n\n3. UNIT 2: LIGHT, ATOMIC STRUCTURE, LEWIS"
" STRUCTURES, GEOMETRY, POLARITY\n* 3.1 EM radiation and photons\n* "
"3.2 Quantization, spectra, photoelectric effect, PES\n* 3.3 Electron"
" configurations and periodic trends\n* 3.4 Valence (bonding capacity"
")\n* 3.5 Lewis structures\n* 3.6 IR spectroscopy (connectivity)\n* "
"3.7 VSEPR geometry (+ skeletal drawings, functional groups)\n* 3.8 "
"Bond and molecular polarity\n\n4. UNIT 3: PREDICTING PROPERTIES "
"(IMFS, MACROMOLECULES, IONIC NETWORKS)\n* 4.1 Molecular or ionic?\n*"
" 4.2 Intermolecular forces (IMFs) (+ mixing and solubility of molecu"
"lar substances)\n* 4.3 Macromolecules and polymers\n* 4.4 Forming "
"ions and formula units\n* 4.5 Coulomb's law and ionic properties\n* "
"4.6 Solubility of ionic compounds\n\n5. UNIT 4: REACTIONS, STOICHIOM"
"ETRY, ENERGY\n* 5.1 Chemical vs physical change; the six reaction "
"assumptions\n* 5.2 Energy diagrams, rate, and extent\n* 5.3 Balancin"
"g equations\n* 5.4 Stoichiometry (+ CO2 emission factor and air-fuel"
" ratio)\n* 5.5 Bond energies and heat of reaction (+ heat and temper"
"ature)",
)
