# C151D18: data for CHEM151. Don't run this file.
D=(
"[5.2 Energy diagrams]\n* DeltaH_rxn = heat of reaction (kJ/mol)\n* "
"E_p = internal potential energy\n* E_a = activation energy (height "
"of the barrier from the starting side)\n* lambda_max = longest wavel"
"ength that can activate a photo-activated reaction\n* [prod]/[react]"
" = ratio of products to reactants at equilibrium\n* P_f, P_b = proba"
"bility of the forward / backward step\n\n[5.4 Stoichiometry]\n* "
"n_A, n_B = moles of substances A and B\n* nu_A, nu_B = their coeffic"
"ients in the balanced equation\n* m = mass (g)\n* M = molar mass "
"(g/mol)\n* EF = kg CO2 released per kg fuel burned (emission factor)"
"\n* %C = mass percent carbon in the fuel\n* m_air, m_fuel = masses "
"of air and fuel (g)\n* AFR = air-fuel mass ratio\n* m_O2 = grams "
"of O2 needed to burn m_fuel grams completely\n* air = 21% O2 / 79% "
"N2 by moles = 23.3% O2 / 76.7% N2 by mass\n* rho = density (liquid: "
"m = rho x V)\n\n[5.5 Bond energy & heat]\n* DeltaH_rxn = heat of "
"reaction (kJ per mole of reaction as written)\n* BE = average bond "
"energy (kJ/mol); breaking bonds absorbs energy (+), forming bonds "
"releases energy (-)\n* q = heat absorbed (+) or released (-) by "
"a sample (J)\n* M_fuel = molar mass of the fuel (g/mol)\n* m = mass "
"(g)\n* c = specific heat capacity (J/(g*degC)), energy to raise "
"1 g by 1 degC; water ~ 4.184\n* DeltaT = T_final - T_initial (degC "
"or K)",
"A\n* A = mass number (protons + neutrons) [2.5]\n* [A] = molarity "
"of solute A (mol/L = M) [2.3]\n* % abundance = percent of atoms "
"that are that isotope [2.6]\n* AFR = air-fuel mass ratio [5.4]\n* "
"air = 21% O2 / 79% N2 by moles = 23.3% O2 / 76.7% N2 by mass [5.4]\n"
"* (aq) = aqueous (dissolved in water) [4.6]\n\nB\n* BE = average "
"bond energy (kJ/mol); breaking bonds absorbs energy (+), forming "
"bonds releases energy (-) [5.5]\n* bonds = number of bonds the atom "
"usually forms (bonding capacity) [3.4]\n\nC\n* %C = mass percent "
"carbon in the fuel [5.4]\n* c = specific heat capacity (J/(g*degC)),"
" energy to raise 1 g by 1 degC; water ~ 4.184 [5.5]\n* c = speed "
"of light (vacuum) = 3.00x10^8 m/s. Use for wavelength <-> frequency "
"[0.1]\n* c = speed of light = 3.00x10^8 m/s (3.00x10^10 cm/s for "
"wavenumbers, lambda in cm) [3.1]\n* chi = electronegativity [3.3]\n*"
" chi_A, chi_B = electronegativities of the two bonded atoms [3.8]\n*"
" chi_AV = their average [3.8]",
"D\n* D = Debye = 3.335x10^-30 C*m [3.8]\n* d = bond length [3.8]\n* "
"d = density (g/mL) [2.2]\n* d = gas density (g/L) [2.4]\n* delta "
"= partial charge in units of e (the more electronegative atom gets "
"delta-, the other delta+, equal magnitude) [3.8]\n* Deltachi = their"
" difference [3.8]\n* DeltaE = energy change (> 0 absorbed, < 0 relea"
"sed) [1.2]\n* DeltaE = energy gap between two levels (J per photon) "
"[3.2]\n* DeltaH_rxn = heat of reaction (kJ per mole of reaction "
"as written) [5.5]\n* DeltaH_rxn = heat of reaction (kJ/mol) [5.2]\n*"
" DeltaT = T_final - T_initial (degC or K) [5.5]",
)
