# C151D17: data for CHEM151. Don't run this file.
D=(
"METHOD: Grams of A -> grams of B\n1. Balance the equation.\n2. Grams"
" A / M_A -> mol A (liquid by volume: m = rho x V; gas: n = PV/RT; "
"solution: n = [A] x V).\n3. mol A x (coefficient B / coefficient "
"A) -> mol B.\n4. mol B x M_B -> grams B.\n\nMETHOD: Limiting reactan"
"t and theoretical yield\n1. Convert every reactant to moles.\n2. "
"Actual ratio = mol X / mol Y; stoichiometric ratio = coef X / coef "
"Y.\n3. Actual < stoichiometric -> X (numerator) is limiting. Actual "
"> stoichiometric -> Y is limiting. Equal -> both used up.\n4. (Short"
"cut: mol / coefficient for each reactant; smallest value = limiting."
")\n5. Theoretical yield = product calculated from the limiting react"
"ant only.\n6. Excess left over = initial mol excess - mol excess "
"used (from the ratio).",
"* DeltaH_rxn = SUM BE(bonds broken, reactants) - SUM BE(bonds formed"
", products)\n* E_p of a molecule (vs free atoms) = -SUM BE of its "
"bonds\n* Per gram of fuel: DeltaH/(coefficient*M_fuel)\n* For a "
"given amount: DeltaH*(mol reacted/coefficient)\n* q = m*c*DeltaT\n* "
"DeltaT = T_final - T_initial",
"* DeltaH_rxn = heat of reaction (kJ per mole of reaction as written)"
"\n* BE = average bond energy (kJ/mol); breaking bonds absorbs energy"
" (+), forming bonds releases energy (-)\n* q = heat absorbed (+) "
"or released (-) by a sample (J)\n* M_fuel = molar mass of the fuel "
"(g/mol)\n* m = mass (g)\n* c = specific heat capacity (J/(g*degC)), "
"energy to raise 1 g by 1 degC; water ~ 4.184\n* DeltaT = T_final "
"- T_initial (degC or K)",
"* Stronger bond = deeper E_p well = more energy to break = more "
"released when formed; bonds don't \"store\" energy\n* E_p of a molec"
"ule relative to free atoms = -SUM BE of its bonds (CH4: -4 x 414 "
"= -1656 kJ/mol)\n* Sign convention: energy released by the system "
"is negative (q = -802 kJ/mol for CH4 combustion)",
"BOND ENERGIES (all in kJ/mol)\n* H-H 436, C-H 414, C-C 347\n* C=C "
"611, C#C 737\n* C-Cl 339, C-N 305, C=N 615\n* C-O 360, C=O 736 (799 "
"in CO2)\n* C-S 259, N-H 389, N-N 163\n* N#N 946, N-O 201, N=O 607\n*"
" O-H 464, O-O 142, O=O 498\n* S-H 368\n\nMETHOD: Estimate DeltaH_rxn"
"\n1. Balance the equation and draw Lewis structures of every species"
".\n2. Count every bond broken in the reactants (x coefficient); "
"add their BEs.\n3. Count every bond formed in the products (x coeffi"
"cient); add their BEs.\n4. DeltaH = broken - formed. Negative -> "
"exothermic. Example: CH4 + 2 O2 -> CO2 + 2 H2O: 4(414) + 2(498) "
"- 2(799) - 4(464) = -802 kJ.\n5. Per gram of fuel: DeltaH / (coeffic"
"ient x M of fuel). For a given amount: DeltaH x (mol reacted / coeff"
"icient).",
"[5.2 Energy diagrams]\n* DeltaH_rxn = E_p,products - E_p,reactants\n"
"* DeltaH_rxn = E_a,forward - E_a,reverse\n* At equilibrium: [prod]/["
"react] = P_f/P_b\n* lambda_max = h*c*N_A/E_a\n\n[5.4 Stoichiometry]\n"
"* n_B = n_A*(nu_B/nu_A)\n* m_B = (m_A/M_A)*(nu_B/nu_A)*M_B\n* Percen"
"t yield = (actual yield/theoretical yield)*100\n* EF_CO2 = (%C/100)*"
"(44.01/12.01)\n* AFR = m_air/m_fuel = (m_O2/0.233)/m_fuel\n\n[5.5 "
"Bond energy & heat]\n* DeltaH_rxn = SUM BE(bonds broken, reactants) "
"- SUM BE(bonds formed, products)\n* E_p of a molecule (vs free atoms"
") = -SUM BE of its bonds\n* Per gram of fuel: DeltaH/(coefficient*M_"
"fuel)\n* For a given amount: DeltaH*(mol reacted/coefficient)\n* "
"q = m*c*DeltaT\n* DeltaT = T_final - T_initial",
)
