# C151D19: data for CHEM151. Don't run this file.
D=(
"E\n* E = energy of ONE photon (J) [3.1]\n* e = electron / proton "
"charge = +/-1.602x10^-19 C. Use for Coulomb problems [0.1]\n* #e^- "
"= number of electrons [2.5]\n* E_a = activation energy (height of "
"the barrier from the starting side) [5.2]\n* E_I = ionization energy"
" (energy to remove an electron) [3.2]\n* E_k = kinetic energy [1.8]\n"
"* E_k = kinetic energy of the ejected electron [3.2]\n* <E_k> = "
"average kinetic energy per particle (J) [1.6]\n* E_molar = energy "
"per mole of photons (J/mol) [3.1]\n* E_p = internal potential energy"
" [5.2]\n* E_p = potential energy (0 when particles are infinitely "
"far apart) [1.8]\n* E_upper, E_lower = energies of the upper and "
"lower levels [3.2]\n* EF = kg CO2 released per kg fuel burned (emiss"
"ion factor) [5.4]\n\nF\n* F = electrostatic force (N) [4.5]\n* f "
"= fractional abundance [2.7]\n* f_L, f_H = fractional abundance "
"of light / heavy isotope [2.7]\n\nG\n* GWP = global warming potentia"
"l; GWP per molecule = how many CO2 molecules equal one molecule "
"of the gas [2.4]\n\nH\n* h = Planck's constant = 6.626x10^-34 J*s "
"[3.1]\n* h = Planck's constant = 6.626x10^-34 J*s. Use for photon "
"energy [0.1]",
"I\n* IMF = intermolecular force [4.2]\n\nK\n* K = 8.988x10^9 N*m^2/C"
"^2 [4.5]\n* k = multiplier: empirical -> molecular formula [2.8]\n* "
"k_B = Boltzmann constant = 1.380x10^-23 J/K [1.7]\n* k_B = Boltzmann"
" constant = 1.380x10^-23 J/K. Use for ideal gas per particle [0.1]\n"
"\nL\n* lambda = wavelength (m) [3.1]\n* lambda_max = longest wavelen"
"gth that can activate a photo-activated reaction [5.2]",
"M\n* M = molar mass (g/mol) [2.2, 2.4, 5.4]\n* m = mass (g) [5.4, "
"5.5]\n* m = mass of gas (g) [2.4]\n* m = mass of one particle (kg) "
"[1.6]\n* m = mass of sample (g) [2.2]\n* m/q = x-axis: mass-to-charg"
"e (~ mass of a +1 ion) [2.7]\n* M^+ = molecular ion (highest-m/q "
"major peak) [2.7]\n* m_1, m_2 = masses of the two isotopes [2.6]\n* "
"m_air, m_fuel = masses of air and fuel (g) [5.4]\n* M_atom = molar "
"mass of one atom (g/mol) [2.2]\n* m_C, m_H, m_O = mass of each eleme"
"nt in the original sample (g) [2.8]\n* m_CO2, m_H2O = masses of "
"products collected (g) [2.8]\n* M_compound = molar mass of the compo"
"und [2.8]\n* M_fuel = molar mass of the fuel (g/mol) [5.5]\n* m_O2 "
"= grams of O2 needed to burn m_fuel grams completely [5.4]\n* m_samp"
"le = mass of the original sample (g) [2.8]\n* M_X = molar mass of "
"element X [2.8]\n* max occupancy = 2 for H, 8 for other nonmetals "
"[3.4]\n* mu = bond dipole moment [3.8]",
)
