# C151D13: data for CHEM151. Don't run this file.
D=(
"* Polarizability (how easily e^- cloud distorts) increases with "
"more electrons, larger size, and elongated/flat shape (more surface "
"contact); branched/spherical -> less contact -> weaker dispersion\n*"
" Dispersion is usually the biggest contributor, even for polar molec"
"ules (dipole-dipole often < 20% of total)\n* H-bond needs: H directl"
"y bonded to N, O, or F in one molecule + N, O, or F with a lone "
"pair in another\n* Stronger IMFs -> higher T_b, T_m, heat of vaporiz"
"ation, viscosity, surface tension; lower vapor pressure (less volati"
"le)\n\nMIXING AND SOLUBILITY OF MOLECULAR SUBSTANCES\n* \"Like disso"
"lves like\": mixing is favored when A-B interactions are about as "
"strong as A-A and B-B\n* Mixing always increases configurations; "
"it fails when one substance's own interactions are much stronger "
"(water won't mix with hexane: H-bonds between water molecules would "
"be lost)\n* PEC view: mixed state lower in E_p and more configuratio"
"ns -> soluble at all T; only one favorable -> solubility depends "
"on T (higher T favors the more-configurations state)\n* Big differen"
"ces in size, composition, or polarity -> immiscible",
"IMF TABLE (interaction: between; strength kJ/mol)\n* Dispersion "
"(induced dipole-induced dipole, London): all molecules; 0.05-40\n* "
"Dipole-induced dipole: polar + nonpolar; 2-10\n* Ion-induced dipole:"
" ion + nonpolar; 3-15\n* Dipole-dipole: polar + polar; 5-25\n* Hydro"
"gen bond: H on N/O/F + lone pair on another N/O/F; 10-40\n* Ion-dipo"
"le: ion + polar (e.g. salt in water); 4-600\n* Covalent bond (for "
"comparison): atoms in a molecule; ~300-570\n\nMETHOD: Rank boiling "
"points (or viscosity, etc.)\n1. Draw each molecule; decide polar "
"or nonpolar (Section 3.8); check for N-H, O-H, F-H.\n2. List IMFs "
"present for each: all have dispersion; polar adds dipole-dipole; "
"N/O/F-H adds H-bonding.\n3. If sizes are very different, the much "
"larger molecule (more e^-, more surface) usually wins -- dispersion "
"dominates.\n4. If sizes are similar: H-bonding > dipole-dipole > "
"dispersion only.\n5. Same formula (isomers): straight chain > branch"
"ed.\n6. Write the justification: \"X has stronger [type] forces "
"because [more electrons / larger surface / polar / H-bonding], so "
"more energy is needed to separate its molecules -> higher T_b.\"",
"* n = number of repeat units in a polymer (subscript on the brackete"
"d repeat unit)\n* R = amino acid side chain",
"* Polymer = many monomers joined by covalent bonds; repeat unit "
"written in brackets with subscript n\n* Functional groups that H-bon"
"d or are polar -> hydrophilic (wetted/dissolved by water); hydrocarb"
"on groups -> hydrophobic\n* Proteins: amino acids (-NH2 + -COOH "
"+ side chain R) joined by peptide bonds (water released)\n* Primary "
"structure = amino acid sequence; secondary = alpha-helix or beta-she"
"et held by H-bonds between N-H and C=O on the backbone; tertiary/qua"
"ternary = overall 3D fold and assembly of chains",
)
