# C151D20: data for CHEM151. Don't run this file.
D=(
"N\n* N = number of particles [1.7, 2.2]\n* n = amount of substance "
"(mol) [2.2]\n* n = moles of gas [2.4]\n* n = number of repeat units "
"in a polymer (subscript on the bracketed repeat unit) [4.3]\n* n "
"= shell number [3.3]\n* n/V = molar concentration of gas (mol/L) "
"[2.4]\n* N_A = Avogadro's number = 6.022x10^23 /mol [2.2]\n* N_A "
"= Avogadro's number = 6.022x10^23 particles/mol. Use for moles <-> "
"particles [0.1]\n* n_A = moles of solute [2.3]\n* n_A, n_B = moles "
"of substances A and B [5.4]\n* N_n = number of neutrons [2.5]\n* "
"nu = frequency (s^-1 = Hz) [3.1]\n* nu_A, nu_B = their coefficients "
"in the balanced equation [5.4]\n* nu~ = wavenumber (cm^-1) [3.6]\n* "
"nu~ = wavenumber (cm^-1, IR spectra) [3.1]\n\nP\n* P = pressure "
"(Pa) [1.7]\n* P = pressure (atm) [2.4]\n* P_f, P_b = probability "
"of the forward / backward step [5.2]\n* PEC = potential energy-confi"
"guration diagram [1.9]\n* ppmv = moles of X per 10^6 moles of air "
"[0.2]\n* [prod]/[react] = ratio of products to reactants at equilibr"
"ium [5.2]\n\nQ\n* q = heat absorbed (+) or released (-) by a sample "
"(J) [5.5]\n* q_1, q_2 = ion charges (C) = (charge number) x 1.602x10"
"^-19 C [4.5]",
"R\n* R = 0.08206 L*atm/(K*mol) [2.4]\n* R = amino acid side chain "
"[4.3]\n* R = gas constant (cal) = 1.986 cal/(K*mol). Use for calorie"
" problems [0.1]\n* R = gas constant (energy) = 8.314 J/(K*mol). "
"Use for energy problems [0.1]\n* R = gas constant (gas law) = 0.0820"
"6 L*atm/(K*mol). Use for PV = nRT with L and atm [0.1]\n* r = distan"
"ce between ion centers (m) ~ cation radius + anion radius [4.5]\n* "
"r.a.m. = average relative atomic mass (amu = g/mol) [2.6]\n* rho "
"= density (liquid: m = rho x V) [5.4]\n\nS\n* (s) = solid [4.6]\n\nT"
"\n* T = absolute temperature (K) [1.7]\n* T = temperature (K) [2.4]\n"
"* T(degC) = temperature in degrees Celsius [0.2]\n* T(K) = temperatu"
"re in kelvin [0.2]\n* T_b = boiling point temperature [1.2]\n* T_m "
"= melting point temperature [1.2]\n\nU\n* ug = microgram (u = micro "
"= 10^-6) [0.2]\n\nV\n* V = volume (L) [2.4]\n* V = volume (m^3) "
"[1.7]\n* <v> = average particle speed (m/s) [1.6]\n* V_m = molar "
"volume of ideal gas at STP = 22.41 L/mol (STP = 273.15 K, 1 atm) "
"[0.1]\n* V_solution = volume of solution (L) [2.3]\n* # valence "
"e^- = number of valence electrons [3.4]",
"X\n* %X = mass percent of element X [2.8]\n* x = fractional abundanc"
"e of isotope 1 (1 - x for isotope 2) [2.6]\n* x-axis = number of "
"configurations [1.9]\n* X_1, X_2 = subscript 1 = initial state, "
"2 = final state; T in K; P and V in any matching units [1.7]\n\nY\n*"
" y-axis = E_p [1.9]\n\nZ\n* Z = atomic number (= number of e^- in "
"a neutral atom) [3.3]\n* Z = atomic number = number of protons (defi"
"nes the element) [2.5]",
)
