# C151D08: data for CHEM151. Don't run this file.
D=(
"[2.2 Mass/mol/particles]\n* n = m/M\n* N = n*N_A\n* m = n*M\n* n "
"= N/N_A\n* M(compound) = SUM(subscript*M_atom)\n* Mass of one partic"
"le = M/N_A (g/particle)\n* Liquid by volume: m = V*d\n\n[2.3 Solutio"
"ns]\n* [A] = n_A/V_solution\n* mass % = (mass of solute/mass of "
"solution)*100\n* n = [A]*V\n* m = n*M\n\n[2.4 Ideal gas (molar)]\n* "
"PV = nRT = (m/M)*R*T\n* M = m*R*T/(P*V)\n* d = P*M/(R*T)\n* n/V "
"= P/(R*T)\n* Other Unit 1 ratio problems: Percent increase = (new-ol"
"d)/old*100\n* Molecules of B per molecule of A = (m_B/M_B)/(m_A/M_A)"
"\n* GWP per molecule = (GWP per gram)*M(gas)/M(CO2)\n\n[2.5 Subatomi"
"c model]\n* A = Z + N_n\n* charge = Z - (#e^-)\n\n[2.6 Avg atomic "
"mass]\n* r.a.m. = SUM(isotope mass * %abundance)/100\n* Two isotopes"
", only average known: x*m_1 + (1-x)*m_2 = average; solve for x\n\n[2"
".7 Mass spectra]\n* Isotope pattern of X2: P(light-light) = f_L^2\n*"
" P(light-heavy) = 2*f_L*f_H\n* P(heavy-heavy) = f_H^2\n\n[2.8 Empiri"
"cal formulas]\n* m_C = m_CO2*(12.01/44.01)\n* m_H = m_H2O*(2*1.008/1"
"8.02)\n* m_O = m_sample - m_C - m_H\n* %X = (subscript of X)*M_X/M_c"
"ompound*100\n* k = M(molecule)/M(empirical), with M(molecule) from "
"the M^+ peak",
"[2.2 Mass/mol/particles]\n* n = amount of substance (mol)\n* m = "
"mass of sample (g)\n* M = molar mass (g/mol)\n* N = number of partic"
"les\n* N_A = Avogadro's number = 6.022x10^23 /mol\n* d = density "
"(g/mL)\n* M_atom = molar mass of one atom (g/mol)\n\n[2.3 Solutions]"
"\n* [A] = molarity of solute A (mol/L = M)\n* n_A = moles of solute\n"
"* V_solution = volume of solution (L)\n\n[2.4 Ideal gas (molar)]\n* "
"P = pressure (atm)\n* V = volume (L)\n* n = moles of gas\n* R = "
"0.08206 L*atm/(K*mol)\n* T = temperature (K)\n* m = mass of gas "
"(g)\n* M = molar mass (g/mol)\n* d = gas density (g/L)\n* n/V = "
"molar concentration of gas (mol/L)\n* GWP = global warming potential"
"; GWP per molecule = how many CO2 molecules equal one molecule of "
"the gas\n\n[2.5 Subatomic model]\n* A = mass number (protons + neutr"
"ons)\n* Z = atomic number = number of protons (defines the element)\n"
"* N_n = number of neutrons\n* #e^- = number of electrons\n\n[2.6 "
"Avg atomic mass]\n* r.a.m. = average relative atomic mass (amu = "
"g/mol)\n* % abundance = percent of atoms that are that isotope\n* "
"x = fractional abundance of isotope 1 (1 - x for isotope 2)\n* m_1, "
"m_2 = masses of the two isotopes\n\n[2.7 Mass spectra]\n* m/q = "
"x-axis: mass-to-charge (~ mass of a +1 ion)\n* M^+ = molecular ion "
"(highest-m/q major peak)\n* f = fractional abundance\n* f_L, f_H "
"= fractional abundance of light / heavy isotope\n\n[2.8 Empirical "
"formulas]\n* m_C, m_H, m_O = mass of each element in the original "
"sample (g)\n* m_CO2, m_H2O = masses of products collected (g)\n* "
"m_sample = mass of the original sample (g)\n* %X = mass percent "
"of element X\n* M_X = molar mass of element X\n* M_compound = molar "
"mass of the compound\n* k = multiplier: empirical -> molecular formu"
"la",
"* lambda*nu = c\n* E = h*nu = h*c/lambda\n* nu~ = 1/lambda\n* E "
"= h*c*nu~\n* Per mole of photons: E_molar = N_A*h*nu (J/mol); divide"
" by 1000 for kJ/mol\n* Shortcut: E(kJ/mol) ~ 1.197x10^5/lambda(nm)\n"
"* Shortcut: E(kJ/mol) ~ 0.01197*nu~(cm^-1)",
)
